name: Build & Push Backend Image
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "backend/server.go"
env:
  AWS_REGION: ap-northeast-1
  ECR_URI: 284968725079.dkr.ecr.ap-northeast-1.amazonaws.com/github-actions-test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Build Docker image
        working-directory: backend
        run: |
          IMAGE_TAG=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
          docker build -t ${{ env.ECR_URI }}:$IMAGE_TAG .
          docker push ${{ env.ECR_URI }}:$IMAGE_TAG
