name: Deploy React App to S3
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "frontend/src/**"
env:
  AWS_REGION: ap-northeast-1
  S3_BUCKET: react-cicd-test-cjadiop
defaults:
  run:
    working-directory: frontend
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build React App
        run: npm run build
      - name: Upload Build files
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: frontend/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download the artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: Configure AWS credentials from account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          # Secretsで登録したキーを設定
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # S3のリージョン
          aws-region: env.AWS_REGION
      - name: Upload to S3
        run: |
          aws s3 ./dist s3:${{ env.S3_BUCKET }}
