name: Deploy React App to S3
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "frontend/src/**"
env:
  AWS_REGION: ap-northeast-1
  S3_BUCKET: react-cicd-test-cjadiop
  VITE_BACKEND_URL: localhost:8000

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
        working-directory: frontend
      - name: Build React App
        run: npm run build
        working-directory: frontend
      - name: Upload Build files
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: frontend/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download the artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: Configure AWS credentials from account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          # Secretsで登録したキーを設定
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # S3のリージョン
          aws-region: ${{ env.AWS_REGION }}
      - name: Upload to S3
        run: |
          aws s3 sync . s3://${{ env.S3_BUCKET }}
      - name: Get CloudFront Distribution Id
        id: cloudfront-id
        run: |
          distribution-id=$(aws cloudfront list-distributions | jq '.DistributionList.Items[0].Id' -r)
          echo "distribution-id=${distribution-id}" >> $GITHUB_OUTPUT
      - name: Clear CloudFront's Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ steps.cloudfront-id.outputs.distribution-id }} --paths "/*"
