name: Manual Backend Deploy

on:
  workflow_dispatch:

env:
  AWS_REGION: ap-northeast-1
  REPOSITORY_SIMULATION: github-actions-test-simulation
  REPOSITORY_BACKEND: github-actions-test
  ECS_CLUSTER: github-actions-test-cluster
  ECS_SERVICE: github-actions-test-service
  TASK_DIFINTION: ./aws/task-definition.json

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build SIMULATION Container Image
        run: |
          cd simulation
          export REPOSITORY=${{ env.REPOSITORY_SIMULATION }}
          docker build -t my-image-simulation .
          docker tag my-image-simulation:latest $REPOSITORY:${{ env.GITHUB_SHA }}-simulation"

      - name: Push SIMULATION Docker Image
        run: |
          cd simulation
          docker push $REPOSITORY:${{ env.GITHUB_SHA }}-simulation

      - name: Build Backend Container Image
        run: |
          cd backend
          export REPOSITORY=${{ env.REPOSITORY_BACKEND }}
          docker build -t my-image-backend .
          docker tag my-image-backend:latest $REPOSITORY:${{ env.GITHUB_SHA }}-backend

      - name: Push Backend Docker Image
        run: |
          cd backend
          docker push $REPOSITORY:${{ env.GITHUB_SHA }}-backend

      - name: Update ECS Task Definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.TASK_DIFINTION }}
          region: ${{ env.AWS_REGION }}
          container-definitions: |
            [
              {
                "name": "simulation-api",
                "image": "${{ env.REPOSITORY_SIMULATION }}:${{ env.GITHUB_SHA }}-simulation",
                ]
              },
              {
                "name": "backend-api",
                "image": "${{ env.REPOSITORY_BACKEND }}:${{ env.GITHUB_SHA }}-backend",
                "portMappings": [
                  {
                    "containerPort": 80,
                    "hostPort": 80,
                    "protocol": "tcp"
                  }
                ]
              }
            ]

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
